# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protoc.interpreter_pb2 as interpreter__pb2


class InterpreterServiceStub(object):
    """The interpreter service is used to run code in a sandboxed environment.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.run = channel.unary_unary(
                '/interpreter.InterpreterService/run',
                request_serializer=interpreter__pb2.InterpreterRequest.SerializeToString,
                response_deserializer=interpreter__pb2.InterpreterResponse.FromString,
                )


class InterpreterServiceServicer(object):
    """The interpreter service is used to run code in a sandboxed environment.
    """

    def run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterpreterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'run': grpc.unary_unary_rpc_method_handler(
                    servicer.run,
                    request_deserializer=interpreter__pb2.InterpreterRequest.FromString,
                    response_serializer=interpreter__pb2.InterpreterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interpreter.InterpreterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InterpreterService(object):
    """The interpreter service is used to run code in a sandboxed environment.
    """

    @staticmethod
    def run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/interpreter.InterpreterService/run',
            interpreter__pb2.InterpreterRequest.SerializeToString,
            interpreter__pb2.InterpreterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
